name: River Contracts CI

on:
  push:
  schedule:
    - cron:  '0 */4 * * *' # every 4 hours, perpetual fuzz testing

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: add node toolchain
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 16.x

      - name: add rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: cache node_modules
        uses: actions/cache@v2
        with:
          path: |
            ./node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: cache cargo root
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo
          key: ${{ runner.os }}-${{ hashFiles('hardhat.config.ts') }}-${{ hashFiles('yarn.lock') }}

      - name: install node dependencies
        run: yarn
      - name: run formatting checks
        run: yarn format:check
      - name: run linting checks
        run: yarn lint:check
      - name: run tests
        run: yarn test
        env:
          FOUNDRY_FUZZ_RUNS: 5000
