name: Mythril Checks
on:
  push:

jobs:
  run-mythril:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        contract:
          - ./contracts/src/River.1.sol
          - ./contracts/src/Oracle.1.sol
          - ./contracts/src/Withdraw.1.sol
          - ./contracts/src/Allowlist.1.sol
          - ./contracts/src/Firewall.1.sol
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Mythril analysis
        uses: ./actions/mythril
        id: mythril-riverv1
        with:
          contract: ${{matrix.contract}}
