name: Mythril Checks
on:
  push:

jobs:
  run-mythril:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        contract:
          - River.1.sol
          - Oracle.1.sol
          - Withdraw.1.sol
          - Allowlist.1.sol
          - Firewall.sol
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Mythril analysis
        uses: ./actions/mythril
        with:
          contract: ./contracts/src/${{matrix.contract}}
        
      - name: Log output
        run: cat mythril_output.md

      - name: Archive myth output
        uses: actions/upload-artifact@v3
        with:
          name: mythril-output-${{ matrix.contract }}
          path: mythril_output.md