name: Tests

on:
  push:
  schedule:
    - cron:  '0 */4 * * *' # every 4 hours, perpetual fuzz testing

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: cache node_modules
        uses: actions/cache@v2
        with:
          path: |
            ./node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: install node dependencies
        run: yarn

      - name: run tests
        run: forge test --force -vvv --gas-report > OUTPUT && cat OUTPUT
        env:
          FOUNDRY_FUZZ_RUNS: 5000

      - name: archive test and gas usage artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-and-gas-usage
          path: |
            OUTPUT